# Generated by Django 2.1.2 on 2018-10-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181024_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='cidade',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
