# Generated by Django 2.1.2 on 2018-10-24 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_consulta_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='cidade',
        ),
    ]
